name = "cocapn"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "COCAPN_KV"
id = "a4f7bf1a6eee40ccabd4389c071046c4"
