/**
 * Integration test: publish → subscribe round trip.
 *
 * Verifies that content published from brain to face is detectable
 * by the subscriber on the other side.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { simpleGit } from "simple-git";
import { SyncPublisher } from "../../src/publishing/sync-publisher.js";
import { Subscriber } from "../../src/publishing/subscriber.js";
import type { Brain, Task } from "../../src/brain/index.js";

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function makeGitRepo(prefix: string): Promise<string> {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  const git = simpleGit(dir);
  await git.init();
  await git.addConfig("user.name", "Test");
  await git.addConfig("user.email", "test@test.com");
  writeFileSync(join(dir, "README.md"), "# Test\n");
  await git.add(".");
  await git.commit("init");
  return dir;
}

function makeStubBrain(): Brain {
  return {
    getSoul: () => "# Test Agent\nA helpful assistant.\n<!-- private -->\nMy secret key\n<!-- /private -->",
    getAllFacts: (mode?: string) => {
      const facts: Record<string, string> = {
        name: "TestAgent",
        version: "1.0",
        "private.apiKey": "sk-deadbeef1234567890",
        "private.dbUrl": "postgres://localhost/secret",
      };
      if (mode === "public") {
        const publicFacts: Record<string, string> = {};
        for (const [k, v] of Object.entries(facts)) {
          if (!k.startsWith("private.")) {
            publicFacts[k] = v;
          }
        }
        return publicFacts;
      }
      return facts;
    },
    readWikiPage: (file: string, _mode?: string) => {
      if (file === "about.md") return "# About\nThis is the public about page.\nContact: agent@example.com";
      return null;
    },
    listWikiPages: () => [
      { file: "about.md", title: "About", excerpt: "" },
    ],
    listTasks: () => [
      { id: "t1", title: "Ship v1", description: "Build the thing", createdAt: new Date().toISOString(), status: "done" },
      { id: "t2", title: "Plan v2", description: "Plan next features", createdAt: new Date().toISOString(), status: "active" },
    ] as Task[],
    getMemories: (_options?: { type?: string; mode?: string }) => [
      {
        id: "m1",
        key: "public.skill",
        value: "coding",
        type: "explicit",
        confidence: 1.0,
        accessCount: 5,
        lastAccessed: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        tags: [],
        autoGenerated: false,
      },
    ],
    getRepoLearner: () => ({
      buildIndex: async () => ({}),
      onCommit: async () => {},
    }),
  } as unknown as Brain;
}

// ─── Integration tests ────────────────────────────────────────────────────────

describe("publish → subscribe round trip", () => {
  let privateDir: string;
  let publicDir: string;

  beforeEach(async () => {
    privateDir = await makeGitRepo("int-priv-");
    publicDir = await makeGitRepo("int-pub-");
  });

  afterEach(() => {
    rmSync(privateDir, { recursive: true, force: true });
    rmSync(publicDir, { recursive: true, force: true });
  });

  it("full round trip: publish from brain, detect changes via subscriber", async () => {
    const brain = makeStubBrain();

    // ── Step 1: Publish ─────────────────────────────────────────────────────
    const publisher = new SyncPublisher({
      privateRepoRoot: privateDir,
      publicRepoRoot: publicDir,
      brain,
    });

    const pubResult = await publisher.publish();

    // Verify publish output
    expect(pubResult.published.length).toBeGreaterThan(0);
    expect(pubResult.committed).toBe(true);
    expect(pubResult.filteredFacts).toContain("private.apiKey");
    expect(pubResult.filteredFacts).toContain("private.dbUrl");

    // Verify files written to face repo
    expect(pubResult.published).toContain("cocapn/public-facts.json");
    expect(pubResult.published).toContain("cocapn/public-soul.md");
    expect(pubResult.published).toContain("cocapn/public-tasks.json");

    // Verify public facts
    const publicFacts = JSON.parse(
      readFileSync(join(publicDir, "cocapn", "public-facts.json"), "utf8")
    );
    expect(publicFacts.name).toBe("TestAgent");
    expect(publicFacts.version).toBe("1.0");
    expect(publicFacts["private.apiKey"]).toBeUndefined();

    // Verify soul has no private section
    const publicSoul = readFileSync(
      join(publicDir, "cocapn", "public-soul.md"),
      "utf8"
    );
    expect(publicSoul).toContain("helpful assistant");
    expect(publicSoul).not.toContain("My secret key");

    // Verify tasks
    const publicTasks = JSON.parse(
      readFileSync(join(publicDir, "cocapn", "public-tasks.json"), "utf8")
    );
    expect(publicTasks).toHaveLength(2);

    // ── Step 2: Simulate external change (commit to face) ────────────────────
    // Add a new file to the face repo (simulating code update)
    writeFileSync(join(publicDir, "new-feature.ts"), "export const x = 1;");
    const faceGit = simpleGit(publicDir);
    await faceGit.add("new-feature.ts");
    await faceGit.commit("feat: add new feature");

    // ── Step 3: Record face HEAD ────────────────────────────────────────────
    const logBefore = await faceGit.log({ maxCount: 1 });
    const shaBefore = logBefore.latest?.hash;

    // Add another commit
    writeFileSync(join(publicDir, "another.txt"), "content");
    await faceGit.add("another.txt");
    await faceGit.commit("add another file");

    const logAfter = await faceGit.log({ maxCount: 1 });
    const shaAfter = logAfter.latest?.hash;

    // SHA should be different
    expect(shaAfter).not.toBe(shaBefore);

    // ── Step 4: Subscriber detects changes ──────────────────────────────────
    // For integration, we directly check that face repo has new commits
    const diff = await faceGit.diffSummary([shaBefore!, shaAfter!]);
    expect(diff.files.length).toBeGreaterThan(0);

    const changedFiles = diff.files.map((f) => f.file);
    expect(changedFiles).toContain("another.txt");
  });

  it("dry-run then publish produces same file list", async () => {
    const brain = makeStubBrain();

    const publisher = new SyncPublisher({
      privateRepoRoot: privateDir,
      publicRepoRoot: publicDir,
      brain,
    });

    const dryResult = await publisher.dryRun();
    const pubResult = await publisher.publish();

    // Published files should match dry-run plan (same content → same files)
    expect(pubResult.published.length).toBe(dryResult.published.length);
    for (const file of dryResult.published) {
      expect(pubResult.published).toContain(file);
    }

    // But only publish actually committed
    expect(dryResult.committed).toBe(false);
    expect(pubResult.committed).toBe(true);
  });

  it("second publish is idempotent (same content, no new commit)", async () => {
    const brain = makeStubBrain();

    const publisher = new SyncPublisher({
      privateRepoRoot: privateDir,
      publicRepoRoot: publicDir,
      brain,
    });

    const first = await publisher.publish();
    expect(first.committed).toBe(true);

    const second = await publisher.publish();
    // Files are written again but git commit may or may not succeed
    // (same content → git may say "nothing to commit")
    expect(second.published.length).toBeGreaterThan(0);
  });
});
