/**
 * Knowledge Pack Export/Import — Share learned patterns across cocapn instances.
 *
 * Knowledge packs are portable JSON files containing memories that can be
 * exported from one instance and imported into another. Use cases:
 *   - Pattern sharing: Agent learns a good pattern in repo A, export to repo B
 *   - Team onboarding: Senior dev exports learned patterns, junior devs import
 *   - Template enrichment: Include knowledge packs in templates for new instances
 *   - Backup: Periodic export of agent's learned knowledge
 */

import { writeFileSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import type { Brain } from "./index.js";
import type { MemoryManager, MemoryEntry } from "./memory-manager.js";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExportOptions {
  minConfidence?: number;  // default 0.5
  tags?: string[];
  types?: string[];
  includeAuto?: boolean;   // default true
}

export interface ImportOptions {
  deduplicate?: boolean;   // default true
  mergeStrategy?: 'skip' | 'overwrite' | 'merge'; // default 'skip'
  tagPrefix?: string;      // e.g. 'imported:repo-a'
}

export interface KnowledgePackMemory {
  key: string;
  value: string;
  type: string;
  confidence: number;
  tags: string[];
}

export interface KnowledgePackStats {
  totalMemories: number;
  avgConfidence: number;
  types: Record<string, number>;
}

export interface KnowledgePack {
  version: string;
  exportedAt: string;
  source: {
    repo: string;
    instance: string;
  };
  memories: KnowledgePackMemory[];
  stats: KnowledgePackStats;
}

export interface ImportResult {
  imported: number;
  skipped: number;
  errors: number;
  conflicts: string[];
}

export interface PreviewResult {
  memories: number;
  conflicts: number;
  conflictKeys: string[];
}

// ─── Knowledge Pack Exporter ───────────────────────────────────────────────────

export class KnowledgePackExporter {
  private brain: Brain;
  private memoryManager?: MemoryManager;

  constructor(brain: Brain, memoryManager?: MemoryManager) {
    this.brain = brain;
    this.memoryManager = memoryManager;
  }

  /**
   * Export memories as a knowledge pack object.
   */
  async export(options?: ExportOptions): Promise<KnowledgePack> {
    const opts = {
      minConfidence: options?.minConfidence ?? 0.5,
      tags: options?.tags,
      types: options?.types,
      includeAuto: options?.includeAuto ?? true,
    };

    let memories: MemoryEntry[] = [];

    if (this.memoryManager) {
      // Export from MemoryManager
      memories = this.memoryManager.list({
        minConfidence: opts.minConfidence,
      });

      // Filter by type if specified
      if (opts.types && opts.types.length > 0) {
        memories = memories.filter(m => opts.types!.includes(m.type));
      }

      // Filter by tags if specified
      if (opts.tags && opts.tags.length > 0) {
        memories = memories.filter(m =>
          opts.tags!.some(tag => m.tags.includes(tag))
        );
      }

      // Filter auto-generated if needed
      if (!opts.includeAuto) {
        memories = memories.filter(m => !m.autoGenerated);
      }
    }

    // Build pack
    const packMemories: KnowledgePackMemory[] = memories.map(m => ({
      key: m.key,
      value: m.value,
      type: m.type,
      confidence: m.confidence,
      tags: m.tags,
    }));

    const stats = this.calculateStats(packMemories);

    return {
      version: "1.0",
      exportedAt: new Date().toISOString(),
      source: {
        repo: this.extractRepoName(),
        instance: this.extractInstanceName(),
      },
      memories: packMemories,
      stats,
    };
  }

  /**
   * Export memories to a file.
   */
  async exportToFile(filePath: string, options?: ExportOptions): Promise<void> {
    const pack = await this.export(options);
    writeFileSync(filePath, JSON.stringify(pack, null, 2) + "\n", "utf8");
  }

  /**
   * Export memories as JSON string.
   */
  async exportToString(options?: ExportOptions): Promise<string> {
    const pack = await this.export(options);
    return JSON.stringify(pack, null, 2);
  }

  private calculateStats(memories: KnowledgePackMemory[]): KnowledgePackStats {
    const total = memories.length;
    const avgConfidence = total > 0
      ? memories.reduce((sum, m) => sum + m.confidence, 0) / total
      : 0;

    const types: Record<string, number> = {};
    for (const mem of memories) {
      types[mem.type] = (types[mem.type] || 0) + 1;
    }

    return { totalMemories: total, avgConfidence, types };
  }

  private extractRepoName(): string {
    try {
      const repoRoot = (this.brain as any).repoRoot as string;
      return repoRoot.split("/").pop() || "unknown";
    } catch {
      return "unknown";
    }
  }

  private extractInstanceName(): string {
    try {
      const repoRoot = (this.brain as any).repoRoot as string;
      return repoRoot; // Use full path as instance identifier
    } catch {
      return "unknown";
    }
  }
}

// ─── Knowledge Pack Importer ───────────────────────────────────────────────────

export class KnowledgePackImporter {
  private brain: Brain;
  private memoryManager?: MemoryManager;

  constructor(brain: Brain, memoryManager?: MemoryManager) {
    this.brain = brain;
    this.memoryManager = memoryManager;
  }

  /**
   * Import a knowledge pack.
   */
  async import(pack: KnowledgePack | string, options?: ImportOptions): Promise<ImportResult> {
    const opts = {
      deduplicate: options?.deduplicate ?? true,
      mergeStrategy: options?.mergeStrategy ?? 'skip',
      tagPrefix: options?.tagPrefix,
    };

    // Parse pack if string
    const parsedPack: KnowledgePack = typeof pack === 'string'
      ? JSON.parse(pack)
      : pack;

    if (!this.isValidPack(parsedPack)) {
      throw new Error("Invalid knowledge pack format");
    }

    const result: ImportResult = {
      imported: 0,
      skipped: 0,
      errors: 0,
      conflicts: [],
    };

    // Get existing keys for deduplication
    const existingKeys = new Set<string>();
    if (this.memoryManager && opts.deduplicate) {
      const existing = this.memoryManager.list();
      for (const mem of existing) {
        existingKeys.add(mem.key);
      }
    } else {
      // Check brain facts
      const facts = this.brain.getAllFacts();
      for (const key of Object.keys(facts)) {
        existingKeys.add(key.replace(/^memory:/, ''));
      }
    }

    // Import each memory
    for (const mem of parsedPack.memories) {
      try {
        // Check for conflicts
        if (existingKeys.has(mem.key)) {
          result.conflicts.push(mem.key);

          if (opts.mergeStrategy === 'skip') {
            result.skipped++;
            continue;
          } else if (opts.mergeStrategy === 'merge') {
            // For merge, skip existing memories
            result.skipped++;
            continue;
          }
          // overwrite: continue with import
        }

        // Add tag prefix if specified
        const tags = opts.tagPrefix
          ? [opts.tagPrefix, ...mem.tags]
          : mem.tags;

        // Import via MemoryManager if available
        if (this.memoryManager) {
          const written = await this.memoryManager.remember(mem.key, mem.value, {
            type: mem.type as any,
            confidence: mem.confidence,
            tags,
          });
          if (written) {
            result.imported++;
          } else {
            result.skipped++;
          }
        } else {
          // Fallback to brain facts
          await this.brain.setFact(`memory:${mem.key}`, mem.value);
          result.imported++;
        }
      } catch (error) {
        result.errors++;
        console.error(`[KnowledgePackImporter] Failed to import ${mem.key}:`, error);
      }
    }

    return result;
  }

  /**
   * Import from a file.
   */
  async importFromFile(filePath: string, options?: ImportOptions): Promise<ImportResult> {
    if (!existsSync(filePath)) {
      throw new Error(`File not found: ${filePath}`);
    }

    const content = readFileSync(filePath, 'utf8');
    return this.import(content, options);
  }

  /**
   * Preview what would be imported without actually importing.
   */
  async preview(pack: KnowledgePack | string): Promise<PreviewResult> {
    // Parse pack if string
    const parsedPack: KnowledgePack = typeof pack === 'string'
      ? JSON.parse(pack)
      : pack;

    if (!this.isValidPack(parsedPack)) {
      throw new Error("Invalid knowledge pack format");
    }

    const conflicts: string[] = [];

    // Get existing keys
    const existingKeys = new Set<string>();
    if (this.memoryManager) {
      const existing = this.memoryManager.list();
      for (const mem of existing) {
        existingKeys.add(mem.key);
      }
    } else {
      const facts = this.brain.getAllFacts();
      for (const key of Object.keys(facts)) {
        existingKeys.add(key.replace(/^memory:/, ''));
      }
    }

    // Find conflicts
    for (const mem of parsedPack.memories) {
      if (existingKeys.has(mem.key)) {
        conflicts.push(mem.key);
      }
    }

    return {
      memories: parsedPack.memories.length,
      conflicts: conflicts.length,
      conflictKeys: conflicts,
    };
  }

  /**
   * Preview from a file.
   */
  async previewFromFile(filePath: string): Promise<PreviewResult> {
    if (!existsSync(filePath)) {
      throw new Error(`File not found: ${filePath}`);
    }

    const content = readFileSync(filePath, 'utf8');
    return this.preview(content);
  }

  private isValidPack(pack: KnowledgePack): boolean {
    return (
      pack &&
      typeof pack === 'object' &&
      typeof pack.version === 'string' &&
      typeof pack.exportedAt === 'string' &&
      pack.source &&
      typeof pack.source.repo === 'string' &&
      typeof pack.source.instance === 'string' &&
      Array.isArray(pack.memories) &&
      pack.stats &&
      typeof pack.stats === 'object'
    );
  }
}
