/**
 * MemoryManager — Self-editing memory with budget, decay, and auto-write.
 *
 * The agent can autonomously write to its own Brain memory when it recognizes
 * learnable moments: debugging solutions, error patterns, user preferences, etc.
 *
 * Features:
 *   - Budget system (max writes per session, max total memories)
 *   - Confidence scoring and decay
 *   - Hybrid search (keyword + semantic)
 *   - Automatic pruning of low-confidence/unaccessed memories
 *   - Safety: duplicates, contradictions, PII detection
 */

import { randomBytes } from "crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import type { Brain } from "./index.js";
import { InvertedIndex } from "../utils/inverted-index.js";

// ─── Types ────────────────────────────────────────────────────────────────────

export type MemoryType = 'explicit' | 'implicit' | 'error_pattern' | 'preference' | 'task_summary';

export interface MemoryWriteOptions {
  type: MemoryType;
  confidence?: number;   // 0-1, default 0.7
  source?: string;       // task/session ID
  tags?: string[];
  expiresAt?: string;    // optional TTL
}

export interface MemoryEntry {
  id: string;
  key: string;
  value: string;
  type: MemoryType;
  confidence: number;
  accessCount: number;
  lastAccessed: string;
  createdAt: string;
  expiresAt?: string;
  source?: string;
  tags: string[];
  autoGenerated: boolean;
}

export interface MemoryManagerOptions {
  maxWritesPerSession?: number;
  maxTotalMemories?: number;
  confidenceThreshold?: number;
  decayDays?: number;
}

export interface MemoryStats {
  total: number;
  autoGenerated: number;
  avgConfidence: number;
  types: Record<string, number>;
  sessionWrites: number;
  remainingBudget: number;
}

export interface PruneResult {
  deleted: number;
  decayed: number;
}

// ─── MemoryManager ─────────────────────────────────────────────────────────────

export class MemoryManager {
  private brain: Brain;
  private memories: Map<string, MemoryEntry>;
  private searchIndex: InvertedIndex;
  private writeCount: number;
  private options: Required<MemoryManagerOptions>;
  private memoriesPath: string;

  constructor(brain: Brain, options?: MemoryManagerOptions) {
    this.brain = brain;
    this.memories = new Map();
    this.searchIndex = new InvertedIndex();
    this.writeCount = 0;
    this.options = {
      maxWritesPerSession: options?.maxWritesPerSession ?? 10,
      maxTotalMemories: options?.maxTotalMemories ?? 1000,
      confidenceThreshold: options?.confidenceThreshold ?? 0.7,
      decayDays: options?.decayDays ?? 30,
    };

    // Memories are stored in cocapn/memory/memories.json
    const repoRoot = (brain as any).repoRoot as string;
    this.memoriesPath = join(repoRoot, "cocapn", "memory", "memories.json");

    this.load();
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Write a memory to the brain.
   * Returns true if written, false if budget exceeded or validation failed.
   */
  async remember(key: string, value: string, options?: MemoryWriteOptions): Promise<boolean> {
    // Check budget
    if (this.writeCount >= this.options.maxWritesPerSession) {
      console.warn("[MemoryManager] Write budget exceeded");
      return false;
    }

    // Check total memory limit
    if (this.memories.size >= this.options.maxTotalMemories) {
      await this.prune();
      if (this.memories.size >= this.options.maxTotalMemories) {
        console.warn("[MemoryManager] Memory limit exceeded");
        return false;
      }
    }

    // Validate
    if (!this.isValidMemory(key, value, options)) {
      return false;
    }

    const confidence = options?.confidence ?? this.options.confidenceThreshold;
    const type = options?.type ?? 'implicit';

    const entry: MemoryEntry = {
      id: this.generateId(),
      key,
      value,
      type,
      confidence,
      accessCount: 0,
      lastAccessed: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      expiresAt: options?.expiresAt,
      source: options?.source,
      tags: options?.tags ?? [],
      autoGenerated: type !== 'explicit',
    };

    this.memories.set(entry.id, entry);
    this.searchIndex.add(entry.id, `${key} ${value}`);
    this.writeCount++;
    this.save();

    // Also write to brain facts for backward compatibility
    if (this.brain) {
      await this.brain.setFact(`memory:${key}`, value);
    }

    return true;
  }

  /**
   * Recall memories based on a query.
   * Uses hybrid search + access count boost.
   */
  async recall(query: string, options?: { limit?: number; minConfidence?: number }): Promise<MemoryEntry[]> {
    const limit = options?.limit ?? 10;
    const minConfidence = options?.minConfidence ?? 0.3;

    // Search by keyword
    const results = this.searchIndex.search(query, limit * 2);
    const scored = new Map<string, number>();

    // Base scores from search
    for (const { id, score } of results) {
      const mem = this.memories.get(id);
      if (mem && mem.confidence >= minConfidence) {
        scored.set(id, score);
      }
    }

    // Boost by access count (logarithmic)
    for (const [id, score] of scored) {
      const mem = this.memories.get(id);
      if (mem) {
        const accessBoost = Math.log1p(mem.accessCount) * 0.1;
        scored.set(id, score + accessBoost);

        // Update access stats
        mem.accessCount++;
        mem.lastAccessed = new Date().toISOString();
      }
    }

    this.save();

    // Sort by boosted score and return top N
    const sorted = Array.from(scored.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
      .map(([id]) => this.memories.get(id)!);

    return sorted.filter(Boolean);
  }

  /**
   * Forget a specific memory by key.
   */
  async forget(key: string): Promise<boolean> {
    for (const [id, mem] of this.memories) {
      if (mem.key === key) {
        this.memories.delete(id);
        this.searchIndex.remove(id);
        this.save();
        return true;
      }
    }
    return false;
  }

  /**
   * Prune old/unused memories.
   * Returns count of deleted and decayed memories.
   */
  async prune(): Promise<PruneResult> {
    const now = Date.now();
    let deleted = 0;
    let decayed = 0;

    for (const [id, mem] of this.memories) {
      // Delete expired memories
      if (mem.expiresAt && new Date(mem.expiresAt).getTime() < now) {
        this.memories.delete(id);
        this.searchIndex.remove(id);
        deleted++;
        continue;
      }

      // Only auto-generated memories are subject to decay
      if (!mem.autoGenerated) continue;

      // Check if memory is stale
      const lastAccess = new Date(mem.lastAccessed).getTime();
      const daysSinceAccess = (now - lastAccess) / (1000 * 60 * 60 * 24);

      if (daysSinceAccess > this.options.decayDays) {
        // Decay confidence
        mem.confidence -= 0.1;
        decayed++;

        // Delete if below threshold
        if (mem.confidence < 0.3) {
          this.memories.delete(id);
          this.searchIndex.remove(id);
          deleted++;
        }
      }
    }

    this.save();
    return { deleted, decayed };
  }

  /**
   * Decay confidence of unused memories (alias for prune).
   */
  async decay(): Promise<number> {
    const result = await this.prune();
    return result.decayed;
  }

  /**
   * Get write count for current session.
   */
  getWriteCount(): number {
    return this.writeCount;
  }

  /**
   * List memories with optional filters.
   */
  list(options?: { type?: MemoryType; minConfidence?: number; autoOnly?: boolean }): MemoryEntry[] {
    let results = Array.from(this.memories.values());

    if (options?.type) {
      results = results.filter(m => m.type === options.type);
    }

    if (options?.minConfidence) {
      results = results.filter(m => m.confidence >= options.minConfidence!);
    }

    if (options?.autoOnly) {
      results = results.filter(m => m.autoGenerated);
    }

    return results.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  }

  /**
   * Get memory statistics.
   */
  stats(): MemoryStats {
    const memories = Array.from(this.memories.values());
    const autoGenerated = memories.filter(m => m.autoGenerated).length;
    const avgConfidence = memories.length > 0
      ? memories.reduce((sum, m) => sum + m.confidence, 0) / memories.length
      : 0;

    const types: Record<string, number> = {};
    for (const mem of memories) {
      types[mem.type] = (types[mem.type] || 0) + 1;
    }

    return {
      total: memories.length,
      autoGenerated,
      avgConfidence,
      types,
      sessionWrites: this.writeCount,
      remainingBudget: this.options.maxWritesPerSession - this.writeCount,
    };
  }

  /**
   * Reset write count (start new session).
   */
  resetSession(): void {
    this.writeCount = 0;
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private generateId(): string {
    return randomBytes(8).toString('hex');
  }

  private isValidMemory(key: string, value: string, options?: MemoryWriteOptions): boolean {
    // Check for duplicates
    for (const mem of this.memories.values()) {
      if (mem.key === key && mem.value === value) {
        return false; // Duplicate
      }
    }

    // Check for contradictions with explicit memories
    if (options?.type !== 'explicit') {
      for (const mem of this.memories.values()) {
        if (mem.key === key && mem.type === 'explicit' && mem.value !== value) {
          return false; // Contradicts explicit memory
        }
      }
    }

    // PII detection (basic patterns)
    const piiPatterns = [
      /\b\d{3}-\d{2}-\d{4}\b/, // SSN
      /\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b/, // Credit card
      /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/, // Email
    ];

    for (const pattern of piiPatterns) {
      if (pattern.test(value)) {
        console.warn("[MemoryManager] PII detected, skipping");
        return false;
      }
    }

    return true;
  }

  private load(): void {
    if (!existsSync(this.memoriesPath)) {
      return;
    }

    try {
      const raw = readFileSync(this.memoriesPath, 'utf8');
      const data = JSON.parse(raw);

      for (const entry of data) {
        this.memories.set(entry.id, entry);
        this.searchIndex.add(entry.id, `${entry.key} ${entry.value}`);
      }
    } catch (error) {
      console.error("[MemoryManager] Failed to load memories:", error);
    }
  }

  private save(): void {
    try {
      const dir = join(this.memoriesPath, "..");
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const data = Array.from(this.memories.values());
      writeFileSync(this.memoriesPath, JSON.stringify(data, null, 2) + "\n", "utf8");
    } catch (error) {
      console.error("[MemoryManager] Failed to save memories:", error);
    }
  }
}
